config/routes.rb
MyBlog::Application.routes.draw do
  root 'index#no_w'

  scope :w do
    get '', to: "index#index", as: :index
    get "a-fighters", to: "index#a_fighters", as: "a_fighters"
    get "maou", to: "index#maou", as: "maou"
    get "shirobako", to: "index#shirobako", as: "shirobako"
    get "jesus", to: "index#jesus", as: "jesus"
  end

end

app/views/index/a_fighters.haml
.a-fighters
  = link_to "⇐ Back", index_path, class: "a-fighters__back"

  .a-fighters__content
    .a-fighters__content__cover
      .a-fighters__logo
        .a-fighters__logo__subtitle 甲級爭取者
        .a-fighters__logo__title A-FIGHTERS

      .a-fighters__text
        A-FIGHTERS was a comic I made during high school. A few years ago, when my MacBook harddrive crashed on me, I thought the work was lost forever. But fate would have it that I rediscover it in my Gmail archive.

      .a-fighters__text Untouched since 2009, A-FIGHTERS in all its glory returns to the internet once more.

      .a-fighters__text.chinese
        「甲級爭取者」是我於高中時期創作的一部漫畫。幾年前，因電腦不幸壞了，讓我以為此作品會永遠消失......但命運使我在郵件箱紀錄中尋回之。

      .a-fighters__text.chinese
        藝術復活, 原作2009版本回到互聯網，「甲級爭取者」現光榮回歸！

    %img.a-fighters__page{src: "http://fc01.deviantart.net/fs71/f/2013/332/a/c/01_by_chesterlaw-d6vxxl1.jpg"}
    %img.a-fighters__page{src: "http://fc02.deviantart.net/fs71/f/2013/332/9/9/02_by_chesterlaw-d6vxxni.jpg"}
    %img.a-fighters__page{src: "http://fc01.deviantart.net/fs70/f/2013/332/4/7/03_by_chesterlaw-d6vxxo7.jpg"}
    %img.a-fighters__page{src: "http://fc02.deviantart.net/fs71/f/2013/332/3/2/04_by_chesterlaw-d6vxxq9.jpg"}
    %img.a-fighters__page{src: "http://fc03.deviantart.net/fs71/f/2013/332/a/9/05_by_chesterlaw-d6vxxqx.jpg"}
    %img.a-fighters__page{src: "http://fc04.deviantart.net/fs71/f/2013/332/a/b/06_by_chesterlaw-d6vxxsq.jpg"}
    %img.a-fighters__page{src: "http://fc08.deviantart.net/fs71/f/2013/332/f/b/07_by_chesterlaw-d6vxxta.jpg"}
    %img.a-fighters__page{src: "http://fc01.deviantart.net/fs71/f/2013/332/0/6/08_by_chesterlaw-d6vxxu3.jpg"}
    %img.a-fighters__page{src: "http://fc01.deviantart.net/fs71/f/2013/332/6/0/09_by_chesterlaw-d6vxxuo.jpg"}
    %img.a-fighters__page{src: "http://fc03.deviantart.net/fs70/f/2013/332/d/3/10_by_chesterlaw-d6vxxvh.jpg"}
    %img.a-fighters__page{src: "http://fc06.deviantart.net/fs70/f/2013/332/e/b/11_by_chesterlaw-d6vxxw7.jpg"}

app/views/index/afighters.html.haml
.a-fighters.page-section-wrapper
  = link_to "< Back", w_path, class: "back"
  
  .page-section
    .cover
      = image_tag "a-fighters.png"

      %p
        A-FIGHTERS was a comic I made during high school. A few years ago, when my MacBook harddrive crashed on me, I thought the work was lost forever. But fate would have it that I rediscover it in my Gmail archive.

      %p Untouched since 2009, A-FIGHTERS in all its glory returns to the internet once more.

      %p.chinese
        「甲級爭取者」是我於高中時期創作的一部漫畫。幾年前，因電腦不幸壞了，讓我以為此作品會永遠消失......但命運使我在郵件箱紀錄中尋回之。

      %p.chinese
        「甲級爭取者」現光榮回歸！

      .red_tab
        %h2.chinese 甲級爭取者
        %h3 藝術復活, 原作2009版本回到互聯網

    %img{src: "http://fc01.deviantart.net/fs71/f/2013/332/a/c/01_by_chesterlaw-d6vxxl1.jpg"}
    %img{src: "http://fc02.deviantart.net/fs71/f/2013/332/9/9/02_by_chesterlaw-d6vxxni.jpg"}
    %img{src: "http://fc01.deviantart.net/fs70/f/2013/332/4/7/03_by_chesterlaw-d6vxxo7.jpg"}
    %img{src: "http://fc02.deviantart.net/fs71/f/2013/332/3/2/04_by_chesterlaw-d6vxxq9.jpg"}
    %img{src: "http://fc03.deviantart.net/fs71/f/2013/332/a/9/05_by_chesterlaw-d6vxxqx.jpg"}
    %img{src: "http://fc04.deviantart.net/fs71/f/2013/332/a/b/06_by_chesterlaw-d6vxxsq.jpg"}
    %img{src: "http://fc08.deviantart.net/fs71/f/2013/332/f/b/07_by_chesterlaw-d6vxxta.jpg"}
    %img{src: "http://fc01.deviantart.net/fs71/f/2013/332/0/6/08_by_chesterlaw-d6vxxu3.jpg"}
    %img{src: "http://fc01.deviantart.net/fs71/f/2013/332/6/0/09_by_chesterlaw-d6vxxuo.jpg"}
    %img{src: "http://fc03.deviantart.net/fs70/f/2013/332/d/3/10_by_chesterlaw-d6vxxvh.jpg"}
    %img{src: "http://fc06.deviantart.net/fs70/f/2013/332/e/b/11_by_chesterlaw-d6vxxw7.jpg"}

app/views/index/dynamic_colors.haml
- @body_classes = 'dynamic-colors'

.content.custom-border-color
  .title.custom-color.custom-border-color Dynamic UI Color Setting

  .paragraph
    .paragraph__corner-border.paragraph__corner-border--top-left.custom-border-color
    .paragraph__corner-border.paragraph__corner-border--top-right.custom-border-color
    .paragraph__corner-border.paragraph__corner-border--bottom-left.custom-border-color
    .paragraph__corner-border.paragraph__corner-border--bottom-right.custom-border-color

    .paragraph__content.custom-color This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content.
    .paragraph__content.custom-color This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content. This is just some filler content.

  .text-block.custom-background
    %h1 Custom Background

.color-chooser.custom-background
  .color-chooser__color-choice.color-chooser__color-choice--red
  .color-chooser__color-choice.color-chooser__color-choice--green
  .color-chooser__color-choice.color-chooser__color-choice--blue

app/views/index/index.haml
- @body_classes = :index

.index__desktop
  .centered-block
    = render 'components/chinese_title'
    = render 'components/merge_title', mobile: false
  = render 'components/mewtwo'
  .centered-block
    = render 'components/social_networks'
    = render 'components/character_design'
    = render 'components/project_list'
    = render 'components/project_list__others'
  .centered-block
    = render 'components/riyarchy_label'

.index__mobile
  = render 'components/merge_title', mobile: true
  = render 'components/project_list'
  = render 'components/project_list__others'

app/views/index/index_12.haml
- @body_classes = :w12

.red-container
  .header-section
    .header
      = image_tag "riyarchy.png"
      %h1 The Riyarchy

  .level.flex
    .section-wrapper.percent-50
      .section
        %p Riyarchy works to remove irrationalities from the world. We have launched multiple efforts to this end.
    .section-wrapper.percent-50
      .section
        %p The eponymous debut, the Riyarchy platform indexes arguments and their refutation arguments indefinitely. Through a cancelling out system, it is determined which arguments are undefeated.

  .level.flex
    .section-wrapper.percent-25
      .section
        %p Please be rational.
    .section-wrapper.percent-75
      .section
        %p Join us, as we construct the argument trees that will end global debates, and ultimately progress humanity.

  .level
    .section-wrapper.percent-100
      .section
        %p The world can't advance, because decisions aren't being made. Under the excuse of "debate rages on," we procrastinate.
  .level
    .section-wrapper.percent-100
      .section
        %p But if arguments were outlined orderly, we can achieve decisive victory.
  .level
    .section-wrapper.percent-100
      .section
        %p Sourced from the collective insight of all humanity, we can draw our conclusions accordingly. Welcome to the Riyarchy.

app/views/index/index_9.haml
- @body_classes = :w9

.title-section
  .h2.title.period-ender
    - @date.each do |character|
      %h2= character
  .h1.title.comma-ender
    - @h1_1.each do |character|
      %h1= character
  .h1.title
    - @h1_2.each do |character|
      %h1= character      
  .h3.title.period-ender.quoter
    - @message_1.each do |character|
      %h3= character
  .h3.title.many-commas
    - @message_2.each do |character|
      %h3= character

.page-section

app/views/index/no_w.html.haml
%p Are you sure this is where you want to go?

app/views/index/w10.haml
- @body_classes = :w10

- 7.times do
  .pixel.clear
- 8.times do
  .pixel.black
- 8.times do
  .pixel.clear

- 6.times do
  .pixel.clear
- 4.times do
  .pixel.black
- 5.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 6.times do
  .pixel.clear

- 4.times do
  .pixel.clear
- 5.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 2.times do
  .pixel.black  
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 6.times do
  .pixel.clear

- 3.times do
  .pixel.clear
- 5.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 2.times do
  .pixel.white
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 2.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 7.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.green
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 2.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 1.times do
  .pixel.red
- 4.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.green
- 1.times do
  .pixel.light-green
- 3.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 2.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 9.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 4.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 2.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 7.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 5.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 3.times do
  .pixel.clear
- 7.times do
  .pixel.black
- 6.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 6.times do
  .pixel.clear

- 4.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 9.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.orange    
- 2.times do
  .pixel.black
- 5.times do
  .pixel.clear

- 5.times do
  .pixel.clear
- 4.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 3.times do
  .pixel.black
- 3.times do
  .pixel.clear

- 9.times do
  .pixel.clear
- 2.times do
  .pixel.black
- 4.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 2.times do
  .pixel.clear

- 4.times do
  .pixel.clear
- 5.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 5.times do
  .pixel.orange
- 3.times do
  .pixel.black

- 2.times do
  .pixel.clear
- 2.times do
  .pixel.black
- 5.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 6.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black

- 1.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 3.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.clear
- 2.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.clear

- 1.times do
  .pixel.black
- 2.times do
  .pixel.white
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 2.times do
  .pixel.white
- 1.times do
  .pixel.black
- 2.times do
  .pixel.white
- 3.times do
  .pixel.black
- 2.times do
  .pixel.clear

- 3.times do
  .pixel.black
- 2.times do
  .pixel.white
- 2.times do
  .pixel.black
- 1.times do
  .pixel.clear
- 2.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 2.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 2.times do
  .pixel.clear

- 2.times do
  .pixel.clear
- 3.times do
  .pixel.black
- 2.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 2.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 1.times do
  .pixel.orange
- 2.times do
  .pixel.black
- 4.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.clear

- 6.times do
  .pixel.clear
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 4.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 6.times do
  .pixel.orange
- 1.times do
  .pixel.black

- 7.times do
  .pixel.clear
- 8.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.black
- 2.times do
  .pixel.white
- 1.times do
  .pixel.black
- 1.times do
  .pixel.white
- 1.times do
  .pixel.orange
- 1.times do
  .pixel.black
- 1.times do
  .pixel.clear

- 13.times do
  .pixel.clear
- 8.times do
  .pixel.black
- 2.times do
  .pixel.clear

app/views/index/w12.haml
- @body_classes = :w12

.red-container
  .header-section
    .header
      = image_tag "riyarchy.png"
      %h1 The Riyarchy

  .level.flex
    .section-wrapper.percent-50
      .section
        %p Riyarchy works to remove irrationalities from the world. We have launched multiple efforts to this end.
    .section-wrapper.percent-50
      .section
        %p The eponymous debut, the Riyarchy platform indexes arguments and their refutation arguments indefinitely. Through a cancelling out system, it is determined which arguments are undefeated.

  .level.flex
    .section-wrapper.percent-25
      .section
        %p Please be rational.
    .section-wrapper.percent-75
      .section
        %p Join us, as we construct the argument trees that will end global debates, and ultimately progress humanity.

  .level
    .section-wrapper.percent-100
      .section
        %p The world can't advance, because decisions aren't being made. Under the excuse of "debate rages on," we procrastinate.
  .level
    .section-wrapper.percent-100
      .section
        %p But if arguments were outlined orderly, we can achieve decisive victory.
  .level
    .section-wrapper.percent-100
      .section
        %p Sourced from the collective insight of all humanity, we can draw our conclusions accordingly. Welcome to the Riyarchy.

app/views/index/w13.haml
- @body_classes = :w13

.content
  .box.one
  .box.two
  .box.three
  .box.four
  .box.five
  .box.six
  .box.seven
  .box.eight
  .box.nine
  .box.ten

app/views/index/w4.haml
- @body_classes = :w4

.page-section
  .red-section
    %h1 CL

  .white-section
    %h2 Hello. I am Chester Law.
    %h3 Hikikomori, Programmer, Kamen Rider. Kamen Ride!

  .red-section
    %ul
      %li Hikikomori
      %li Programmer
      %li Kamen Rider

app/views/index/w5.haml
- @body_classes = :w5

.title-bar
  %h1
    %span Chester
    %span> Law

  .white-block
  %h2 I am me.

app/views/index/w6.haml
- @body_classes = :w6

.title-bar
  %h1
    Chester
    %br
    Law

  .footer
    %p Terms
    %p Privacy
    %p= "\u00A9 #{Time.new.year} Chester Law"

.page-section
  %p This is Chester Law's Website.
  %p I don't like to use UI Frameworks like Bootstrap or Foundation, because they make your site look like everyone else's.
  %p Also, it's annoying to learn about the taken up keywords and how to use the framework. It's really just easier for me to write my own grid system. I don't really get why that's the main selling feature of these frameworks. Just set some divs to 50% each, and you have a responsive site! Then when the viewport comes to a breakpoint like, say 480px, just do a media query to set them to be display block and width 100%.
  %p We even have flexbox now to save the day!